name: alerta_me_flutter
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0-218.1.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

  flutter_localization: ^0.2.2
  form_validator: ^2.1.1
  mobx: ^2.2.0
  provider: ^6.0.5
  dio: ^5.1.2
  flutter_mobx: ^2.0.6+5
  flutter_easyloading: ^3.0.5
  go_router: ^14.2.8
  time_range_picker: ^2.3.0
  expandable_page_view: ^1.0.17
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  convert: ^3.1.1
  fl_chart: ^0.69.0
  timelines: ^0.1.0
  shared_preferences: ^2.2.3
  google_fonts: ^6.2.1
  skeletonizer: ^1.4.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mobx_codegen: ^2.3.0
  build_runner: ^2.4.4

flutter:
  uses-material-design: true