name: alerta_me_flutter
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0-218.1.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0

  cupertino_icons: ^1.0.2
  flutter_localization: ^0.1.10
  google_sign_in: ^6.1.2
  form_validator: ^2.1.1
  mobx: ^2.2.0
  provider: ^6.0.5
  dio: ^5.1.2
  flutter_mobx: ^2.0.6+5
  flutter_easyloading: ^3.0.5
  shared_preferences: ^2.1.1
  go_router: ^9.0.3
  skeletons: ^0.0.3
  time_range_picker: ^2.2.0
  expandable_page_view: ^1.0.17
  firebase_auth: ^4.9.0
  firebase_core: ^2.15.1
  mask_text_input_formatter: ^2.5.0

  pointycastle: ^3.7.3
  convert: ^3.1.1
  encrypt: ^5.0.3
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mobx_codegen: ^2.3.0
  build_runner: ^2.4.4

flutter:
  uses-material-design: true